function field(name, i, kv) {
  for (i = 1; i <= NF; i++) {
    split($i, kv, "=")
    if (kv[1] == name)
      return kv[2]
  }
  return ""
}

function fail(reason) {
  print "rv32im perf check failed: " reason > "/dev/stderr"
  failed = 1
}

BEGIN {
  expected["mapped_alu:cold"] = 1
  expected["mapped_alu:warm"] = 1
  expected["memory_read:cold"] = 1
  expected["memory_read:warm"] = 1
  expected["branch_chain:cold"] = 1
  expected["branch_chain:warm"] = 1
  expected["mixed:cold"] = 1
  expected["mixed:warm"] = 1

  guest_insns["mapped_alu:cold"] = 256
  guest_insns["mapped_alu:warm"] = 32768
  guest_insns["memory_read:cold"] = 48
  guest_insns["memory_read:warm"] = 3072
  guest_insns["branch_chain:cold"] = 63
  guest_insns["branch_chain:warm"] = 8064
  guest_insns["mixed:cold"] = 61
  guest_insns["mixed:warm"] = 3904

  state_hash["mapped_alu:cold"] = "0x011b51b6"
  state_hash["mapped_alu:warm"] = "0x89018a9d"
  state_hash["memory_read:cold"] = "0xb9e5c390"
  state_hash["memory_read:warm"] = "0xb9e5c390"
  state_hash["branch_chain:cold"] = "0x7615e4db"
  state_hash["branch_chain:warm"] = "0x1c8bb6b0"
  state_hash["mixed:cold"] = "0x403e59d4"
  state_hash["mixed:warm"] = "0x403e59d4"

  memory_hash["mapped_alu:cold"] = "0x811c9dc5"
  memory_hash["mapped_alu:warm"] = "0x811c9dc5"
  memory_hash["memory_read:cold"] = "0x5fbb5540"
  memory_hash["memory_read:warm"] = "0x28f6afc5"
  memory_hash["branch_chain:cold"] = "0x811c9dc5"
  memory_hash["branch_chain:warm"] = "0x811c9dc5"
  memory_hash["mixed:cold"] = "0xc45006d7"
  memory_hash["mixed:warm"] = "0xb8a06245"

  scheduler_hash["mapped_alu:cold"] = "0x1c430938"
  scheduler_hash["mapped_alu:warm"] = "0xaaeb39c5"
  scheduler_hash["memory_read:cold"] = "0x084354f4"
  scheduler_hash["memory_read:warm"] = "0x1e4d33c5"
  scheduler_hash["branch_chain:cold"] = "0x1171fe38"
  scheduler_hash["branch_chain:warm"] = "0x35da79c5"
  scheduler_hash["mixed:cold"] = "0x76e1433c"
  scheduler_hash["mixed:warm"] = "0xea4b69c5"

  trace_hash["mapped_alu:cold"] = "0x2d938744"
  trace_hash["mapped_alu:warm"] = "0x70d241c5"
  trace_hash["memory_read:cold"] = "0x3f285294"
  trace_hash["memory_read:warm"] = "0xc648afc5"
  trace_hash["branch_chain:cold"] = "0x0a69f0a4"
  trace_hash["branch_chain:warm"] = "0x23e541c5"
  trace_hash["mixed:cold"] = "0x1bfebbf4"
  trace_hash["mixed:warm"] = "0x3bea2fc5"

  cold_instret_max["mapped_alu"] = 110942
  cold_instret_max["memory_read"] = 31201
  cold_instret_max["branch_chain"] = 27801
  cold_instret_max["mixed"] = 30221
  warm_instret_max["mapped_alu"] = mapped_alu_instret_max
  warm_instret_max["memory_read"] = memory_read_instret_max
  warm_instret_max["branch_chain"] = branch_chain_instret_max
  warm_instret_max["mixed"] = mixed_instret_max
  bytes_max["mapped_alu"] = mapped_alu_bytes_max
  bytes_max["memory_read"] = memory_read_bytes_max
  bytes_max["branch_chain"] = branch_chain_bytes_max
  bytes_max["mixed"] = mixed_bytes_max
}

/ command=rv32im-perf / {
  result = field("result")
  workload = field("workload")
  phase = field("phase")

  if (result != "PASS")
    fail("non-PASS line for " workload ":" phase)

  key = workload ":" phase
  if (key in expected) {
    seen[key]++
    if (field("counter_source") != "qemu_exec_trace")
      fail(key " missing deterministic qemu instruction source")
    if (field("rdinstret_csr_repeatable") != "0")
      fail(key " did not label qemu-user rdinstret instability")
    if ((field("guest_insns") + 0) <= 0)
      fail(key " missing guest instructions")
    if ((field("guest_insns") + 0) != guest_insns[key])
      fail(key " guest instruction count changed")
    if ((field("rv32_instret") + 0) <= 0)
      fail(key " missing retired instructions")
    if ((field("generated_blocks") + 0) <= 0 ||
        (field("generated_bytes") + 0) <= 0)
      fail(key " missing generated-code evidence")
    if ((field("fallbacks") + 0) != 0 ||
        (field("execute_arm_calls") + 0) != 0)
      fail(key " used an interpreter fallback")
    if (field("state_hash") == "" || field("memory_hash") == "" ||
        field("scheduler_hash") == "" || field("trace_hash") == "")
      fail(key " missing correctness hashes")
    if (field("state_hash") != state_hash[key] ||
        field("memory_hash") != memory_hash[key] ||
        field("scheduler_hash") != scheduler_hash[key] ||
        field("trace_hash") != trace_hash[key])
      fail(key " correctness hash changed")
    if ((field("generated_bytes") + 0) > bytes_max[workload])
      fail(key " generated bytes exceeded ceiling")
    if (phase == "cold")
      instret_max = cold_instret_max[workload]
    else
      instret_max = warm_instret_max[workload]
    if ((field("rv32_instret") + 0) > instret_max)
      fail(key " retired instructions exceeded ceiling")
    if (phase == "cold" && (field("translations") + 0) <= 0)
      fail(key " did not include translation")
    if (phase == "warm" && (field("translations") + 0) != 0)
      fail(key " unexpectedly translated code")
  }

  if (workload == "control" && phase == "probe")
    control_seen++
  if (workload == "empty" && phase == "control")
    empty_seen++
  if (workload == "all" && phase == "summary")
    summary_seen++
}

END {
  for (key in expected) {
    if (seen[key] != 1)
      fail("expected exactly one " key " result")
  }
  if (control_seen != 1)
    fail("missing rdinstret control result")
  if (empty_seen != 1)
    fail("missing measurement overhead result")
  if (summary_seen != 1)
    fail("missing suite summary")
  if (failed)
    exit 1
  print "RV32IM mapped_alu baseline warm_instret=" mapped_alu_baseline_instret \
    " generated_bytes=" mapped_alu_baseline_bytes
  print "RV32IM deterministic perf check passed"
}
